Update GitHub Actions workflow: streamline dependency installation and detect package manager dynamically

diff --git a/portfolio/.github/workflows/deploy.yml b/portfolio/.github/workflows/deploy.yml
--- a/portfolio/.github/workflows/deploy.yml
+++ b/portfolio/.github/workflows/deploy.yml
@@ -18,10 +18,6 @@ concurrency:
 jobs:
   build:
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: portfolio
-
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -31,7 +27,22 @@ jobs:
         with:
           node-version: "20"
           cache: 'npm'
-          cache-dependency-path: portfolio/package-lock.json
+
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "./portfolio/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+          elif [ -f "./portfolio/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
 
       - name: Setup Pages
         uses: actions/configure-pages@v4
@@ -39,10 +50,10 @@ jobs:
           static_site_generator: next
 
       - name: Install dependencies
-        run: npm install
+        run: cd portfolio && npm ${{ steps.detect-package-manager.outputs.command }}
 
       - name: Build with Next.js
-        run: npm run build
+        run: cd portfolio && npm run build
         env:
           NEXT_PUBLIC_BASE_PATH: /portfolio
 
